Vagrant.configure("2") do |config|
  config.vm.define "aelidrysS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "aelidrysS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      curl -sfL https://get.k3s.io | sh -
      chmod 644 /etc/rancher/k3s/k3s.yaml
    SHELL
  end
end
