SERVER_IP = "192.168.56.110"
SERVER_HOSTNAME = "aelidrysS"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = SERVER_HOSTNAME
  config.vm.network "private_network", ip: SERVER_IP

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 3
  end

  # Install K3s
  config.vm.provision "shell",
    path: "scripts/install_k3s.sh",
    env: { "NODE_IP" => SERVER_IP }

  # Wait until K3s is ready before applying manifests
  config.vm.provision "shell", inline: <<-SHELL
    echo "⏳ Waiting for K3s to be ready..."
    until kubectl get nodes >/dev/null 2>&1; do
      sleep 2
    done

    kubectl apply -f /vagrant/confs
  SHELL
end