HOST_IP = "192.168.56.10"


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "forwarded_port", guest: 80, host: 8055

  config.vm.network "private_network", ip: HOST_IP

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 2
  end


  config.vm.provision "shell",
    path: "scripts/install_gitlab.sh",
    env: {"HOST_IP" => HOST_IP}
  

end
